version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: doviz_postgres
    environment:
      POSTGRES_DB: doviz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 03806
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=1000'

  grafana:
    image: grafana/grafana:latest
    container_name: doviz_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - postgres

volumes:
  postgres_data:
  grafana_data: 